### ISSUE TITLE
floj unit tests are hanging/failing

### ISSUE THREAD

**Issue by cchrysostom** [desotoinc/floj#1]
```
testTransactionsRetain(org.floj.core.ParseByteCacheTest)  Time elapsed: 0.039 sec  <<< ERROR!
java.nio.BufferUnderflowException
    at org.floj.core.ParseByteCacheTest.testTransaction(ParseByteCacheTest.java:373)
    at org.floj.core.ParseByteCacheTest.testTransactionsRetain(ParseByteCacheTest.java:153)

Running org.floj.core.PeerAddressTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.floj.core.PeerAddressTest
Running org.floj.core.PeerGroupTest
```

**Comment by rengelking** [comment]
Hi Chris, I couldn't get those unit tests to work with Bitcoinj, so I didn't update them for my part of the work, as it could be a couple of month long project; I just translated Bitcoinj to work with floj, but I didn't repair any of bitcoinj's inherent problems.

**Comment by cchrysostom** [comment]
Okay, thanks, that's good to know. We'll (the floj community, I hope) attack them later.

**Comment by trentlarson** [comment]
In Bitcoinj, tags `v0.14.7` and the master branch pass all tests for me without any changes; previous versions require skipping the `PaymentSessionTest` and ignoring testless projects thus: `-Dtest='!PaymentSessionTest' -DfailIfNoTests=false`  (The version tagged `segwit` also requires skipping KeyChainGroupTest, eg. `-Dtest='!PaymentSessionTest,!KeyChainGroupTest' -DfailIfNoTests=false`)

Currently in this project, there are 4 tests that hang, so we have to run the following in order to bypass those tests:
`mvn package -Dtest='!FilteredBlockAndPartialMerkleTreeTests,!PeerGroupTest,!PeerTest,!TransactionBroadcastTest'`
That gives the output: `Tests run: 5119, Failures: 347, Errors: 153, Skipped: 4`

I could see skipping those 4 tests (maybe they require additional, network-related infrastructure?), though I have a feeling they'll work after other unit tests are fixed.

@rengelking What version of bitcoinj did you fork (against which you couldn't get unit tests to work)?

**Comment by cchrysostom** [comment]
Looking over the non-hanging test, I think close to all of them are related to the changes of parameters from Bitcoint to FLO. I've created a new branch, `failing-tests-repair`, that will be for fixing code or the tests to pass.

**Comment by cchrysostom** [comment]
For those helping with the tests, create your own branch for a fix then a pull request from yours to `failing-tests-repair`.
