### ISSUE TITLE
floj error when running mainnet and testnet

### ISSUE THREAD

**Issue by cchrysostom** [desotoinc/floj#3]
```
12:58:34 23 Peer.blockChainDownloadLocked: blockChainDownloadLocked(0000000000000000000000000000000000000000000000000000000000000000): ignoring duplicated request: a939b5c2f2a9d7430f833a9ffc1ecd7eb433add3671677809cbf6b8bdc1430ec
12:58:34 23 Peer.blockChainDownloadLocked: java.lang.Throwable
    at org.floj.core.Peer.blockChainDownloadLocked(Peer.java:1454)
    at org.floj.core.Peer.processHeaders(Peer.java:735)
    at org.floj.core.Peer.processMessage(Peer.java:505)
    at org.floj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:145)
    at org.floj.net.ConnectionHandler.handleKey(ConnectionHandler.java:224)
    at org.floj.net.NioClientManager.handleKey(NioClientManager.java:87)
    at org.floj.net.NioClientManager.run(NioClientManager.java:123)
    at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
    at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
    at org.floj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:50)
    at java.lang.Thread.run(Thread.java:745)
```

Error appears in logs but does not fail application when running `wallettemplate`.

**Comment by rengelking** [comment]
I have seen it encounter a number of problems like this and continue on... this is a built in feature of bitcoinj, not abnormal for it

**Comment by bitspill** [comment]
My understanding of that section of code that is a debug status line but had no ill effects and is associated with  the `block does not connect` message and leading up spam of duplicate block received occurring at the same time that was mentioned in Rocket.Chat

https://github.com/dloa/floj/blob/master/floj-core/src/main/java/org/floj/core/Peer.java#L1402-L1456

Specifically this section
```
// Once it has decided which blocks we need, it will send us an inv with up to 500 block messages. We may
// have some of them already if we already have a block chain and just need to catch up. Once we request the
// last block, if there are still more to come it sends us an "inv" containing only the hash of the head
// block.
//
// That causes us to download the head block but then we find (in processBlock) that we can't connect
// it to the chain yet because we don't have the intermediate blocks. So we rerun this function building a
// new block locator describing where we're up to.
```
