### ISSUE TITLE
Fix creation of private key from BIP 32 format

### ISSUE THREAD

**Issue by trentlarson** [desotoinc/floj#6]
Bitcoinj allows for creation of a private key with the BIP 32 "tprv" format.

Here's an example, where we added Florincoin parameters to Bitcoinj: https://github.com/OverstockMedici/bitcoinj/compare/1700ec0be4fe50a1b7ea95d6af0e46f876746333...OverstockMedici:master

Here's the set of commands to use that library:

```
$ kotlinc-jvm -cp core/target/bitcoinj-core-0.15.med.1-SNAPSHOT-bundled.jar
Welcome to Kotlin version 1.2.41 (JRE 1.8.0_171-b11)
Type :help for help, :quit for quit
>>> val privStr = "tprv8ZgxMBicQKsPf6jw5tHhF6RbXT197jVU5W4KghzHjSoPDEW1bjAeK2q3p8Pg8wHyjL93U96Lksgz3X3csHRRZiuwXQ9rELzydSrbLjc2y8f"
>>> val netParams = org.bitcoinj.params.FloTestNetParams.get()
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
>>> val key = org.bitcoinj.crypto.DeterministicKey.deserializeB58(privStr, netParams)
>>> key
DeterministicKey{pub=02c554077cefd36e899041dbb958a2ad87f626ffd14f10a6ce106c518841ad6d9d, chainCode=dfa825d74106df14bcb6f00105876119bb6ed676da53b9342a5a68de8c6bc475, path=M, isEncrypted=false, isPubKeyOnly=false}
```

(BTW, if you like Scala, you can see the same success if you substitute "scala" for "kotlinc-jvm" on the first line.)

However, here's what we get with the current code:

```
$ kotlinc-jvm -cp  floj-core/target/floj-core-0.14.8-SNAPSHOT-bundled.jar
Welcome to Kotlin version 1.2.41 (JRE 1.8.0_171-b11)
Type :help for help, :quit for quit
>>> val privStr = "tprv8ZgxMBicQKsPf6jw5tHhF6RbXT197jVU5W4KghzHjSoPDEW1bjAeK2q3p8Pg8wHyjL93U96Lksgz3X3csHRRZiuwXQ9rELzydSrbLjc2y8f"
>>> val netParams = org.floj.core.NetworkParameters.fromID(org.floj.core.NetworkParameters.ID_TESTNET)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
>>> val key = org.floj.crypto.DeterministicKey.deserializeB58(privStr, netParams)
java.lang.IllegalArgumentException: Unknown header bytes: tprv
	at org.floj.crypto.DeterministicKey.deserialize(DeterministicKey.java:524)
	at org.floj.crypto.DeterministicKey.deserializeB58(DeterministicKey.java:506)
	at org.floj.crypto.DeterministicKey.deserializeB58(DeterministicKey.java:497)
```

**Comment by trentlarson** [comment]
The prefixes are now: mainnet Fprv & Fpub and testnet Fprt & Fput

So the following privStr works with MainNetParams: Fprv4rbspRQ4B6uzrjVMXW8X1qvKSSPCwhLMioosvjGDRSxd4RmeKkrQcNHHCMv23w5GML6umzGoERtS4D58G3dwbw5Bsg24awx9QY1364ywTHH

**Comment by cchrysostom** [comment]
@trentlarson The DeSoto bitcoinj repo is not public. For the benefit of community devs, would you mind copy and pasting your example above? It is fine to use a Gist, too. Thanks.
